# Generated by Django 3.0.7 on 2020-06-12 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['pub_date']},
        ),
        migrations.RenameField(
            model_name='blogger',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='blogger',
            name='last_name',
            field=models.CharField(default='default_last_name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miniblog.Blogger'),
        ),
    ]
