# Generated by Django 3.0.7 on 2020-06-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0009_comment_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
