# Generated by Django 3.0.7 on 2020-06-21 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0010_auto_20200621_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miniblog.Blog'),
        ),
    ]
