# Generated by Django 3.0.7 on 2020-06-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0011_auto_20200622_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(help_text='Enter comment about blog here.', max_length=1000),
        ),
    ]
