# Generated by Django 3.0.7 on 2020-07-01 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miniblog', '0013_auto_20200623_0342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'default_related_name': 'blogs', 'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
