# Generated by Django 3.0.7 on 2020-07-04 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0016_auto_20200702_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 4, 15, 18, 55, 778003), null=True),
        ),
    ]
