# Generated by Django 3.0.7 on 2020-08-17 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0028_auto_20200704_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 0, 53, 56, 191875)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 18, 0, 53, 56, 192321), null=True),
        ),
    ]
