# Generated by Django 3.0.7 on 2020-08-19 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0030_auto_20200818_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='autodescription',
            field=models.TextField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 21, 6, 40, 220951)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 21, 6, 40, 221456)),
        ),
    ]
