# Generated by Django 3.0.7 on 2020-08-19 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0033_auto_20200819_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='autodescription',
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 21, 8, 51, 554830)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 21, 8, 51, 555279)),
        ),
    ]
