# Generated by Django 3.0.7 on 2020-08-19 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0039_auto_20200819_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='autodescription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 21, 33, 0, 534830)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 21, 33, 0, 535327)),
        ),
    ]
