# Generated by Django 3.0.7 on 2020-08-19 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0042_auto_20200820_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='autodescr_test',
            field=models.TextField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='descr_test',
            field=models.TextField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 2, 8, 31, 340240)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 2, 8, 31, 340757)),
        ),
    ]
