# Generated by Django 3.0.7 on 2020-08-19 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0043_auto_20200820_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='autodescr_test',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='descr_test',
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 2, 14, 7, 46161)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 2, 14, 7, 46666)),
        ),
    ]
