# Generated by Django 3.0.7 on 2020-08-19 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0046_auto_20200820_0231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='somemodel',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='somemodel',
            name='field_1_text',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='somemodel',
            name='field_2_text',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 2, 43, 32, 533917)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 2, 43, 32, 534418)),
        ),
    ]
