# Generated by Django 3.0.7 on 2020-08-20 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0054_auto_20200820_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 40, 47, 317865)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 40, 47, 317352)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 40, 47, 317326)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 40, 47, 317847)),
        ),
    ]
