# Generated by Django 3.0.7 on 2020-08-21 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0056_auto_20200821_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 10, 19, 55, 717782)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 10, 19, 55, 717757)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 10, 19, 55, 718268)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 10, 19, 55, 718252)),
        ),
    ]
