# Generated by Django 3.0.7 on 2020-08-21 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0057_auto_20200821_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='autodescription',
        ),
        migrations.AlterField(
            model_name='blog',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 11, 18, 50, 302111)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 11, 18, 50, 302087)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 11, 18, 50, 302566)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 11, 18, 50, 302551)),
        ),
    ]
