# Generated by Django 3.0.7 on 2020-09-21 18:36

import datetime
from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0058_auto_20200821_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='blog',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 21, 36, 5, 515099)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 21, 36, 5, 515077)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 21, 36, 5, 515588)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 21, 36, 5, 515570)),
        ),
    ]
