# Generated by Django 3.0.7 on 2020-09-21 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0059_auto_20200921_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 21, 58, 45, 59659)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 21, 58, 45, 59625)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='mod_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 21, 58, 45, 60470)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 21, 58, 45, 60434)),
        ),
    ]
